CC = gcc
CFLAGS = -Wall -Werror -g

SOURCES1 = my-cat.c
OBJECTS1 = $(SOURCES1:.c=.o)
EXECUTABLE1 = my-cat

SOURCES2 = my-sed.c
OBJECTS2 = $(SOURCES2:.c=.o)
EXECUTABLE2 = my-sed

SOURCES3 = my-uniq.c
OBJECTS3 = $(SOURCES3:.c=.o)
EXECUTABLE3 = my-uniq

all: $(EXECUTABLE1) $(EXECUTABLE2) $(EXECUTABLE3)

$(EXECUTABLE1): $(OBJECTS1)
	$(CC) $(OBJECTS1) -o $@

$(EXECUTABLE2): $(OBJECTS2)
	$(CC) $(OBJECTS2) -o $@

$(EXECUTABLE3): $(OBJECTS3)
	$(CC) $(OBJECTS3) -o $@

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS1) $(OBJECTS2) $(OBJECTS3) $(EXECUTABLE1) $(EXECUTABLE2) $(EXECUTABLE3)